
package org.openxdata.server.module.openclinica.ws.userlist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import org.openxdata.server.module.openclinica.ws.userlist.GetUsersResponse;
import org.openxdata.server.module.openclinica.ws.userlist.Ws;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/usersGet/v1", wsdlLocation = "file:/h:/ws/usersGetWsdl.wsdl.xml")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface Ws {


    /**
     * 
     * @param getUsersRequest
     * @return
     *     returns org.openxdata.server.module.openclinica.ws.userlist.GetUsersResponse
     */
    @WebMethod
    @WebResult(name = "getUsersResponse", targetNamespace = "http://openclinica.org/ws/usersGet/v1", partName = "getUsersResponse")
    public GetUsersResponse getUsers(
        @WebParam(name = "getUsersRequest", targetNamespace = "http://openclinica.org/ws/usersGet/v1", partName = "getUsersRequest")
        Object getUsersRequest);

}
