
package org.openxdata.server.module.openclinica.ws.studylist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import org.openxdata.server.module.openclinica.ws.studylist.GetStudyListResponse;
import org.openxdata.server.module.openclinica.ws.studylist.Ws;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/studyListGet/v1", wsdlLocation = "h:/wsl/studyListGetWsdl.wsdl.xml")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface Ws {


    /**
     * 
     * @param getStudyListRequest
     * @return
     *     returns org.openxdata.server.module.openclinica.ws.studylist.GetStudyListResponse
     */
    @WebMethod
    @WebResult(name = "getStudyListResponse", targetNamespace = "http://openclinica.org/ws/studyListGet/v1", partName = "getStudyListResponse")
    public GetStudyListResponse getStudyList(
        @WebParam(name = "getStudyListRequest", targetNamespace = "http://openclinica.org/ws/studyListGet/v1", partName = "getStudyListRequest")
        Object getStudyListRequest);

}
