
package org.openxdata.server.module.openclinica.ws.eventlist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import org.openxdata.server.module.openclinica.ws.eventlist.GetEventListRequest;
import org.openxdata.server.module.openclinica.ws.eventlist.GetEventListResponse;
import org.openxdata.server.module.openclinica.ws.eventlist.Ws;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/eventListGet/v1", wsdlLocation = "h:/ws/eventListGetWsdl.wsdl.xml")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface Ws {


    /**
     * 
     * @param getEventListRequest
     * @return
     *     returns org.openxdata.server.module.openclinica.ws.GetEventListResponse
     */
    @WebMethod
    @WebResult(name = "getEventListResponse", targetNamespace = "http://openclinica.org/ws/eventListGet/v1", partName = "getEventListResponse")
    public GetEventListResponse getEventList(
        @WebParam(name = "getEventListRequest", targetNamespace = "http://openclinica.org/ws/eventListGet/v1", partName = "getEventListRequest")
        GetEventListRequest getEventListRequest);

}
